<?xml version="1.0"?>
<package format="2">
  <name>uav_system</name><version>0.1.0</version>
  <description>ROS1 Native PX4: uav_system</description>
  <maintainer email="liuhestu@users.noreply.github.com">liu he</maintainer>
  <license>GPL-3.0-or-later</license>
  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>state_source_manager</exec_depend>
  <exec_depend>state_adapter</exec_depend>
  <exec_depend>flight_supervisor</exec_depend>
  <exec_depend>px4_backend</exec_depend>
  <exec_depend>commander</exec_depend>
  <exec_depend>mavros</exec_depend>
  <exec_depend>mavros_extras</exec_depend>
  <exec_depend>realsense2_camera</exec_depend>
  <exec_depend>ov_msckf</exec_depend>

</package>
